### ISSUE TITLE
Reset password issue

### ISSUE THREAD

**Issue by retrodans** [popeen/Popeens-DSub#100]
I installed the software on a Windows 10 machine.  I reset the password, but it didn't seem to take (could not login).  So I then went to reset my password, but when I did this, it gave me the below error message.

Exception | java.lang.NullPointerException
-- | --
Message | null
Java version | Oracle Corporation 1.8.0_201
Operating system | Windows 10 10.0
Server | jetty-6.1.x
Memory | Used 43 of 55 MB
Stack trace | java.lang.NullPointerException 	at java.net.URLEncoder.encode(Unknown Source) 	at java.net.URLEncoder.encode(Unknown Source) 	at net.tanesha.recaptcha.ReCaptchaImpl.checkAnswer(ReCaptchaImpl.java:63) 	at net.sourceforge.subsonic.controller.MultiController.recover(MultiController.java:109) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 	at java.lang.reflect.Method.invoke(Unknown Source) 	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:473) 	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:410) 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153) 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571) 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1093) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:265) 	at org.acegisecurity.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:107) 	at org.acegisecurity.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:72) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:166) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.wrapper.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:81) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:110) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:149) 	at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084) 	at net.sourceforge.subsonic.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:43) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084) 	at net.sourceforge.subsonic.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:54) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084) 	at net.sourceforge.subsonic.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:59) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084) 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360) 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181) 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712) 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405) 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139) 	at org.mortbay.jetty.Server.handle(Server.java:313) 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506) 	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:844) 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:644) 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211) 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381) 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396) 	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)

**Comment by retrodans** [comment]
I think this may be a requirement issue on windows.  Is there a specific version of java I should have?  I am currently on Java 8 update 201.

Sadly I cannot use this app at the moment, but once this is sorted, I would like to start, as it sounds like exactly what I need.

Thanks for the work

**Comment by popeen** [comment]
The password reset issue should be fixed in the latest server version that was released as a pre-release a few days ago. Try installing that and if you are still having problems after that let me know
