### ISSUE TITLE
BookSonic does not see files correctly (Docker)

### ISSUE THREAD

**Issue by goose-ws** [popeen/Popeens-DSub#117]
Files do not appear unless a specific chain of events is followed.

Steps to Reproduce:
1. Install BookSonic in Docker via the DockStarter tool
2. Ensure that my user has permissions to access the media folder
3. Verify that the `/audiobooks` volume is mounted correctly, and readable inside the docker container. I did this by connecting to a console in the container, `cd`ing to the directory, opening the files with `head`, and verifying write permissions with `touch`. The directory structure I'm using is: `/audiobooks/Andy Weir/The Martian/The Martian (Unabridged).flac`
4. Add the media folder via `Settings > Media folders > Name "Audio Books" > Folder "/audiobooks" > Enabled "X"`
5. Click `Save`
6. Click `Scan media folders now`
7. Return to `Home`, see that no media is present.
8. Return to `Settings > Media folders`, change the path for `Audio Books` to `/audiobooksss` (A directory which does not exist)
9. Click `Save`
10. Click `Scan media folders now`
11. Change the path for `Audio Books` to `/audiobooks` (The correct/actual directory)
12. Click `Save`
13. Click `Scan media folders now`
14. Return to `Home`, where my media is now present.

Another user reported similar behavior on Reddit ([link](https://old.reddit.com/r/Booksonic/comments/byyaks/not_recognizing_files_not_sure_if_anyone_is/) who was told it was an issue related to their files being on Google Drive. My files are on a local drive, `/mnt/storage` is a MergerFS mount point of `/mnt/disk*` -- However, all disks are local and connected directly via LSI.

**Comment by popeen** [comment]
As this tracker is for the Android app I have opened the issue in the correct tracker and will be closing this one. The new issue can be found at https://github.com/popeen/Popeens-Subsonic/issues/52
