### ISSUE TITLE
Easier setup, first start

### ISSUE THREAD

**Issue by popeen** [popeen/Popeens-DSub#14]
Make it easier to setup the server.
First time app is started guide user through setting it up

**Comment by BlinkyStitt** [comment]
I found using Docker to be very quick and easy. I think recommending that will lead to the simplest instructions that will work well enough on every OS.  Keep up the great work :)

**Comment by popeen** [comment]
The docker container is great but this repo is for the app, the server is at https://github.com/popeen/Popeens-Subsonic

Added login screen in fc2395b

**Comment by BlinkyStitt** [comment]
Aha. I thought this issue was about making it easy to run a server for developing the app against rather than making the setup page in the app simpler.
