### ISSUE TITLE
Persistent notification fails after about 30 seconds

### ISSUE THREAD

**Issue by Basaingeal** [popeen/Popeens-DSub#162]
I have the Persistent Notification setting on and it works somewhat. When the setting is off, the notification goes away as soon as I pause. But with it on it stays but doesn't stay for very long. 

I listen on earbuds a lot and I'll tap them to pause for a minute and when I tap them again, nothing happens. I open my phone and the notification is gone.

This doesn't happen with my podcast or music apps. I can leave them paused indefinitely and continue listening. But with Booksonic, if I go 30 seconds paused, then in order to start playing again, I need to reopen the app and hit play.

I'm not sure if this has to do with memory optimization or what, but no other audio apps I use have this problem.

**Comment by popeen** [comment]
I was able to replicate this before but have not been able to do it with 2201, most likely targeting a newer SDK fixed it. If you are still having this problem with the latest version please reopen the issue
