### ISSUE TITLE
Remember sleeptimer on next play

### ISSUE THREAD

**Issue by popeen** [popeen/Popeens-DSub#163]
Originally from #71

Remember to keep using sleeptimer (start over) when pressing play after the times has stopped it

**Comment by abremhol** [comment]
Would be really nice to have this feature. This is what keeps me from not switching over from smart audiobook player.

**Comment by popeen** [comment]
d4ec8cbe323e353dcb4c5e9d2baab7e1293181c1 adds a setting for auto sleep timer. When enabled there will always be a sleep timer of set value unless a One-time timer is set to override it. The timer can be turned off as usual and will then come back next time you start something unless the setting is disabled.
