### ISSUE TITLE
Using widgets (in Android 10/11) or persistent media controls in Android 11 to play media causes audiobook to restart

### ISSUE THREAD

**Issue by ColonelSanderson** [popeen/Popeens-DSub#185]
Pressing play on widgets or persistent media controls, or in the app after it's been closed for a while shows the playback slider at 0:00. Pressing play will often result in the book being replayed from the beginning, and previous bookmarks lost.

**Comment by ChiefMedicalOfficer** [comment]
![20201201_231403](https://i.imgur.com/pvC6pfc.png)

I'm experiencing this too on Android 8.
Hitting 'back'  from the above screen will take me to the correct location within the book though. I'll email my logs if it'll help any.

**Comment by Toblun** [comment]
i also have this happening

**Comment by popeen** [comment]
I have not been able to replicate this in 2201, might be that targeting later versions of the SDK fixed it.
Will leave this open for a while to make sure, if anyone experiences this on 2201 or later, please let me know

**Comment by popeen** [comment]
Used to see it from time to time before but have not been able to reproduce in 2201+ despite daily use, I will close this now as it is most likely fixed. If anyone still have this issue please open another issue and refer to this one
