### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by bjoerns1983** [popeen/Popeens-DSub#190]
Hi there,
i just installed the Booksonic App for my daughter and have seen that there seems to be no support for other UI Languages than english. 
If you would tell me which files i have to touch i would like to help you out with a german translation.

**Comment by popeen** [comment]
Hi,

Sorry for the late answer but that's great!
The file that would need translating is this one
https://github.com/popeen/Booksonic-App/blob/master/app/src/main/res/values/strings.xml

For strings that you can't/don't think need translating you can simply remove them from your translation file and the app will use the default (english) string instead.

If you want to submit a pull request it should be placed in a folder called values-de 
See swedish translation as example
https://github.com/popeen/Booksonic-App/tree/master/app/src/main/res/values-sv/strings.xml

You could also just post the translated file here if you prefer

oh, and thank you! Any help on the project is appreciated and especially translations as that is something I definitely can't do myself!

**Comment by ghost** [comment]
[strings_ger.zip](https://github.com/popeen/Booksonic-App/files/15127504/strings_ger.zip)

Please find this German translation.
With many thanks to DeepL and 
http://colorofbest.com/en/android-string-translate/ 

;-)
