### ISSUE TITLE
Change playback speed

### ISSUE THREAD

**Issue by popeen** [popeen/Popeens-DSub#20]
Add an option to change playback speed

**Comment by popeen** [comment]
Added in 66681f2

**Comment by garyo** [comment]
Thanks for this! But 1.5x is already very fast for podcasts. Cam we have a 1.1x or 1.2x option?

**Comment by popeen** [comment]
Glad you like it but I can't really take credit for it. It was added in the latest version of DSub.

I tweaked it a bit in 771d36b and 1.2x was added there. The current options are 0.5, 1.0, 1.2, 1.5 and 2.0 but thats not set in stone and could change later on.
