### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by gamegoofs2** [popeen/Popeens-DSub#211]
I imported the project into Android Studio 4.2 and Gradle failed to sync a dependency. Here is the error I am getting.

> Starting Gradle Daemon...
Gradle Daemon started in 4 s 68 ms
IO exception while downloading manifest:
java.io.FileNotFoundException: https://dl.google.com/android/repository/sys-img/google-tv/sys-img2-1.xml

and

> Gradle sync failed: Could not resolve all dependencies for configuration ':app:flossDebugRuntimeClasspath'.
				Could not create task ':app:minifyFlossFixWithR8'.
				Cannot query the value of this provider because it has no value available. (32 s 266 ms)
				

How do I resolve this? Sorry if this isn't even related to the app.

**Comment by popeen** [comment]
Seems like Google have solved this as I am able to sync the project without errors on a newly installed machine

**Comment by hmlendea** [comment]
This seems to still happen, at least for me:
```
Could not determine the dependencies of task ':app:compileFlossDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:flossDebugCompileClasspath'.
   > Could not resolve project :ServerProxy.
     Required by:
         project :app
      > No matching configuration of project :ServerProxy was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'version' with value 'floss' but:
          - None of the consumable configurations have attributes.
```

On Arch Linux (x86, 64bit)

EDIT: Nevermind, I forgot to run `git submodule update --init` after cloning this repo. Seems to be working now
