### ISSUE TITLE
Timer function keeps resetting when phone locks.

### ISSUE THREAD

**Issue by LilSlippinJimmy** [popeen/Popeens-DSub#222]
I'm having an issue where the timer doesn't function and keeps resetting, it's not just my device, a friend with a google pixel gets the same results.

Steps:
1. Start playing audio.
2. Set a 5min timer
3. Lock the phone
4. Unlock the phone
5. Change apps
6. Go back to Booksonic
7. Timer will never go past 4:20 ish, it'll keep going back to 4:59

Device:
Samsung galaxy S21 Ultra, Android 11.

Booksonic:
Latest from play store.

**Comment by popeen** [comment]
Have you moved the phone anything during this?
The sleep timer has a "shake function" where it will reset any time the phone is shook

**Comment by popeen** [comment]
Will be closing this as I believe the comment above is the reason aka it is working as expected, let me know if you think this is wrong.

I have plans for making this feature optional but it is not at the moment

**Comment by popeen** [comment]
e7e17bfc0d800197128149156c494e6d0c3b8baa added the feature to disable shake to reset, can be found under settings > Playback

This will be available in the playstore beginning with version 2202
