### ISSUE TITLE
Please support higher speeds, preferably 5x, but at least 3x

### ISSUE THREAD

**Issue by jostwald** [popeen/Popeens-DSub#249]
Hi, I'd like to use your app, but I generally listen at 2.5x, and sometimes as high as 4 (and I'd like the ability to go higher).   Is there any chance you could support higher speed playback?

**Comment by popeen** [comment]
At the moment you can go as high as 3 by using the slider on the playback speed selector. But sure, I see no problem with allowing higher speeds then this so I'll add that, probably in the mars release.

**Comment by jostwald** [comment]
Great! Thank you!

**Comment by popeen** [comment]
Will be in mars release in a few days

**Comment by jostwald** [comment]
Thank you!
