### ISSUE TITLE
Server Check

### ISSUE THREAD

**Issue by miketweaver** [popeen/Popeens-DSub#39]
My current server address is as follows: `https://hostname.com/booksonic/`
When I enter that in, it says I'm not using a booksonic server. 
When I remove the trailing slash, (`https://hostname.com/booksonic`) it correctly determines that it's a booksonic server.

**Comment by popeen** [comment]
Should be an easy fix and done in the next release. Thanks

**Comment by popeen** [comment]
To add to this the message is also shown when the server is offline

**Comment by popeen** [comment]
Trailing / fixed in a255f1f
Offline issue fixed in 54e0b05
