### ISSUE TITLE
Folder Not Found

### ISSUE THREAD

**Issue by madmoneymike5** [popeen/Popeens-DSub#41]
I'm copying and pasting the directory where my audio books are (C:\Users\mich\Google Drive\Plex Only Media\Audio Books) directly out of my Window's 10 File Explorer. However, Booksonic Server is unable to find that folder. I tried step by step to make this work, starting with C:\, then C:\Users\, then C:\Users\mich\, etc. It works with C:\Users\mich\Google Drive\, but C:\Users\mich\Google Drive\Plex Only Media\ fails.

**Comment by popeen** [comment]
See popeen/Popeens-Subsonic#22
