### ISSUE TITLE
Can't connect to server / can in mobile browser

### ISSUE THREAD

**Issue by gdeyoung** [popeen/Popeens-DSub#46]
I get an error connecting to the server in the app.  Running Nexus 6 with 6.0.1.  When adding the server in the settings and testing the connection, I get a "Connection Failure.  A problem occurred communicating with the server".  However, when I tap the open in the browser it goes right to the booksonic login page and can login in the mobile browser.  The app is online and it does work with the demoserver.  Ideas to troubleshoot?

**Comment by popeen** [comment]
No, sorry no ideas at the top of my head, if you could send me a log file I can have a look at it and see if I can help, most likely it will be shown there. 

You can find an option to send logs by tapping the three dots at the top right of the screen on the first view of the app. 
OBS, i you have compiled the app yourself you need to add a pastbin key in _app/src/main/java/github/popeen/dsub/util/EnvironmentVariables.java_  for the send log feature to work.

**Comment by popeen** [comment]
Since I haven't heard anything back I'm assuming you found the problem, if not let me now
