### ISSUE TITLE
Jukebox mode not working

### ISSUE THREAD

**Issue by tuxflo** [popeen/Popeens-DSub#47]
I'm trying to get the jukebox mode working for using the phone as remote control for the server.
If I switch to the Jukebox when playing a track it does not play anything on the server and the slider jumps between 0 and 4 seconds.
The jukebox mode via browser works fine, server plays sound and skipping tracks is possible too.

EDIT: I think it must be a server side issue, a different subsonic android client has the same problem too. Can you move the issue to the other repository?

**Comment by popeen** [comment]
Moved to popeen/Popeens-Subsonic#26
