### ISSUE TITLE
Cannot log in on local browser. Getting Error 503

### ISSUE THREAD

**Issue by Jakesparrow** [popeen/Popeens-DSub#49]
This is what comes up when trying to access on web now:

HTTP ERROR: 503

SERVICE_UNAVAILABLE
RequestURI=/

Powered by jetty://

It has been working fine for a while now, but this just started in the past week or two.
Tried going from v1.0 to beta 1.1 and still the same error.

Any ideas? 
Thanks

-Jake

**Comment by popeen** [comment]
Server problem, moved to popeen/Popeens-Subsonic#27
