### ISSUE TITLE
automatic bookmarking when pausing

### ISSUE THREAD

**Issue by nrjohnstone** [popeen/Popeens-DSub#62]
I've noticed that compared to MortPlayer, which is another audiobook app for playing local files, this app is lacking when it comes to remembering where you were when listening to an audiobook.

For example, if I am listening to an audiobook, and I am 1:15:30 into it, then I pause and back out into the menu to switch to something else, if I come back to that same book and hit the track again it immediately starts playing the book again from the start.... not fun trying to find where you were if it's a single 6 hour audio book.

Without digging into the code, it appears that the client at least might remember where you were, as a blue bookmark icon does appear next to the track maybe indicating it knows that you were listening to it... so all that should happen is that if you have 1 or more bookmarks against a track, it should resume at the lastest bookmark (that is the bookmark furtherest through the track).

**Comment by popeen** [comment]
As a note on this, if you click the play icon on the top right instead of the individual track it will ask you if you want to continue where you left off.

This however is not that obvious and should be fixed so that you can just select the track

**Comment by popeen** [comment]
Fixed in ef6fd58b2945aa411a8c4e36b1ae335eabd05878
