### ISSUE TITLE
RSS Download Error

### ISSUE THREAD

**Issue by j0nnymoe** [popeen/Popeens-DSub#63]
Hi,

Having an issue adding the following podcast: http://rss.acast.com/adambuxton , Not sure if its related to the feed itself or booksonic. I've got other podcasts working fine within booksonic.

I am running the LinuxServer.io docker of booksonic [ https://hub.docker.com/r/linuxserver/booksonic/ ]

Please let me know if there is anything I can test.

Thanks

**Comment by popeen** [comment]
This is a problem with the Booksonic server and not the app.
The Booksonic server is deprecated and will be replaced soon, therefore I am closing this issue without crossposting it on the servers issue tracker.
