### ISSUE TITLE
Insane battery drain

### ISSUE THREAD

**Issue by keaganhilliard** [popeen/Popeens-DSub#65]
I've noticed that Booksonic is draining my Pixel's battery like crazy. I used to get a couple of days out of my battery cycle. I am now lucky to get a few hours. My settings app shows that Booksonic is using 102%. Let me know if there is any information that you might need to troubleshoot.

Device: Pixel
OS: Android 8.0

**Comment by popeen** [comment]
This is most likely due to DLNA, see https://github.com/daneren2005/Subsonic/issues/751

If you go to Settings -> Casting (inside the app) there is a setting called "DLNA Enabled", make sure that the checkbox there is not checked, that should fix the problem for you
