### ISSUE TITLE
Android booksonic app will not authenticate to booksonic server when authenticating with LDAP

### ISSUE THREAD

**Issue by rogue780** [popeen/Popeens-DSub#68]
My booksonic server uses LDAP authentication for all accounts except admin. From the webpage login, I can login fine with `user`/`P@ssw0Rd`, which is an LDAP login. When using the Android app, however, I get an error saying I've entered the wrong username or password. I can, however, login as `admin` from the app.

**Comment by hjone72** [comment]
I believe this is related to: https://github.com/airsonic/airsonic/issues/260

**Comment by hjone72** [comment]
Tracked it down to this here: https://github.com/popeen/Popeens-DSub/blob/master/app/src/main/java/github/popeen/dsub/util/Util.java#L400

Basically Booksonic is not correctly handling the app posting the md5 and salt.

**Comment by StudioEtrange** [comment]
Hello
This issue is still true ?
Cannot use LDAP auth in booksonic-air when using android booksonic-app  ?

**Comment by hjone72** [comment]
> Hello
> This issue is still true ?
> Cannot use LDAP auth in booksonic-air when using android booksonic-app ?

Not too sure, I haven't made the plunge into the new server or app. (don't fix what ain't broke or something). But based on this issue logged... https://github.com/popeen/Booksonic-Air/issues/24

**Comment by popeen** [comment]
Sorry for the late fix on this. I have implemented a work around for it and I will push a public beta to the playstore tonight.

The work around is a server specific setting in the app that forces the app to send the password instead of a token in the API calls. I don't consider this a real fix and will look in to it more soon but at least for now it will be possible to use LDAP.

**Comment by popeen** [comment]
I will close this issue and handle it in popeen/Booksonic-Air#24 as the core problem is server side and the app now has a setting that makes it work
