### ISSUE TITLE
Sometimes fails to detect downloaded files after update to Android 8.0

### ISSUE THREAD

**Issue by zerodogg** [popeen/Popeens-DSub#76]
I have a Galaxy S7, which was recently updated to Android 8.0. Now I have a rather strange issue with booksonic. The app works fine most of the time, but often, after Android has terminated the application (normally) for some reason or another, when I open it up, it doesn't detect any of the files that have been downloaded (the blue pin is not listed), and it just hangs if I try to play something, and sometimes also when I refresh the bookmarks list.

If I "force close" the app, and then empty the cache for the app (the android cache that you can empty through the app manager, not the file cache that's inside the app), then it works, until the next time android closes it. This issue was not there before the update.

I'm using booksonic from Google Play.

**Comment by zerodogg** [comment]
This issue is still valid. Also occurs on Galaxy S8 and S9 running Android 8.0.

**Comment by popeen** [comment]
Unfortunately I have not been able to replicate this problem, I just pushed an update to Google Play (1.0.19) that should go live in a few hours. Please check if this is still a problem in that version. 

If it is, next time it happens please send me a log file. You can do that from the main screen of the app. Tap on the three dots at the top right corner and then on Send log.
Please send the log before you force close the app.

**Comment by zerodogg** [comment]
This appears to have been resolved in the latest update. Thank you very much :+1: :)
