### ISSUE TITLE
Issue with Mobile App v 1.0.17 Crashing / Not Resuming

### ISSUE THREAD

**Issue by codog180** [popeen/Popeens-DSub#78]
On Android 8.0 the newest version of the mobile app crashes and will not resume it's place. After leaving the screen and going back to the app it will not respond. The window will open but nothing will work, buttons, menus, etc... The only way to recover is to force kill the app and then clear the cache. Screen shot is of what is displayed when trying to go back to the app after leaving the window. Eventually the app will crash. 
![screenshot_20190212-132938_booksonic](https://user-images.githubusercontent.com/8893424/52673185-c2f08d80-2ed4-11e9-996c-b2841b659d92.jpg)

**Comment by popeen** [comment]
This has been fixed in later releases
