### ISSUE TITLE
Server v1.1- java.io.FileNotFoundException: lastUpdateCheck

### ISSUE THREAD

**Issue by wptex** [popeen/Popeens-DSub#81]
Just updated to 1.1 using Windows installer in Windows 7 x64. Getting the following popup occasionally: "java.io.FileNotFoundException: lastUpdateCheck (The system cannot find the file specified)"
![booksonic1 1-update-error](https://user-images.githubusercontent.com/25441014/57486089-ee380e00-7272-11e9-9747-d44d984f033f.png)

Did not receive this error previously with 1.1beta. Booksonic appears to function normally otherwise.

EDIT: this applies to popeen/Popeens-Subsonic (oops)

**Comment by popeen** [comment]
Closing as this was for the legacy server
