### ISSUE TITLE
Ply does nothing

### ISSUE THREAD

**Issue by knmens** [popeen/Popeens-DSub#83]
I can connect to the server using the BookSonic Android app. In that app i can see the books and their descriptions.  When I push play nothing happens.  I'm so close to success.

**Comment by popeen** [comment]
I am sorry for the late reply, for quicker replies please email support@ptjwebben.se

When you tap play do tap the play button at the top or the bottom?
The bottom play icon will only work if you have already selected a track to play. Try tapping on the first track of the book or the play icon at the top and see if it works out better for you.
