### ISSUE TITLE
How to add Booksonic service to Sonos controller...

### ISSUE THREAD

**Issue by MrMxyzptlk** [popeen/Popeens-DSub#85]
Thank you for an excellent app!

I'm using BS 1.1 and have enabled Sonos in the config. I cannot find this service in add services in the Sonos app; does the service have a different name?

**Comment by popeen** [comment]
The service name should be Subsonic.
That said, this is a leftover feature from the Subsonic server Booksonic is based on. I don't have access to a Sonos device so I have not been able to verity that it actually works.
